#!/bin/bash

TIKA_VERSION=2.7.0
export f=$1

java -classpath \
  "./tika-build/tika-app-${TIKA_VERSION}.jar:./tika-build/tika-parser-nlp-package-${TIKA_VERSION}.jar:./location-ner-model:./geotopic-mime" \
  -Dorg.apache.tika.mime.custom-mimetypes=./geotopic-mime/org/apache/tika/mime/custom-mimetypes.xml \
  org.apache.tika.cli.TikaCLI -m "$f"